@host=http://localhost:10001

### 两个状态顺序工作流
POST /run/start
Host: {{host}}
Content-Type: application/x-yaml

config:
  kind: workflow
  name: demo/two-parallel
  metadata:
    title: 两状态并行
  spec:
    states:
      - name: initial
        title: 开始
        emitter: system/start
        emitterRules: [ auto-start ]
        transitions:
          - event: start
            targets:
              - state: a
                prefetchers: [ demo/request-targets ]
              - state: b
                prefetchers: [ demo/request-targets ]
      - name: a
        title: 并行A
        emitter: demo/approval
        emitterRules: [ veto, any-accept ]
        transitions:
          - event: passed
            targets:
              - state: end
                prefetchers: [ ]
          - event: rejected
            targets:
              - state: end
                prefetchers: [ ]
      - name: b
        title: 并行B
        emitter: demo/approval
        emitterRules: [ veto, any-accept ]
        transitions:
          - event: passed
            targets:
              - state: end
                prefetchers: [ ]
          - event: rejected
            targets:
              - state: end
                prefetchers: [ ]
      - name: end
        title: 结束
inputParameters: [ ]
