@host=http://localhost:10001

### 两个状态顺序工作流
POST /run/start
Host: {{host}}
Content-Type: application/x-yaml

config:
  kind: workflow
  name: demo/workflow
  metadata:
    title: 未命名工作流
  spec:
    states:
      - name: initial
        title: 开始
        emitter: system/start
        emitterRules:
          - auto-start
        transitions:
          - event: start
            targets:
              - state: state_1777160072770
                prefetchers:
                  - demo/request-targets
      - name: state_1777160072770
        title: 任务1
        transitions:
          - event: passed
            targets:
              - state: state_1777160089724
                prefetchers:
                  - demo/request-targets
          - event: rejected
            targets:
              - state: end
                prefetchers: [ ]
        emitterRules:
          - veto
          - any-accept
        emitter: demo/approval
      - name: state_1777160089724
        title: 任务2
        transitions:
          - event: passed
            targets:
              - state: end
                prefetchers: [ ]
          - event: rejected
            targets:
              - state: end
                prefetchers: [ ]
        emitterRules:
          - veto
          - any-accept
        emitter: demo/approval
      - name: end
        title: 结束
        transitions: [ ]
    layout:
      states:
        initial:
          x: 329
          y: 50
        state_1777160072770:
          x: 329
          y: 200
        state_1777160089724:
          x: 329
          y: 350
        end:
          x: 332
          y: 617
      transitions:
        initial::start:
          x: 374
          y: 125
        state_1777160072770::passed:
          x: 374
          y: 275
        state_1777160072770::rejected:
          x: 154
          y: 275
        state_1777160089724::passed:
          x: 374
          y: 425
        state_1777160089724::rejected:
          x: 154
          y: 425
inputParameters: [ ]
