@host=http://localhost:10001

### 新建emitter
POST /emitters/
Host: {{host}}
Content-Type: application/x-yaml

kind: workflow-transition-emitter
name: demo/approval
metadata:
  title: 审批场景 emitter
spec:
  allowedActions:
    - action: ACCEPT
      title: 通过
    - action: REFUSE
      title: 拒绝
  allowedEvents:
    - name: passed
      title: 通过
    - name: rejected
      title: 拒绝

### 新建emitter
POST /emitters/
Host: {{host}}
Content-Type: application/x-yaml

kind: workflow-transition-emitter
name: system/start
metadata:
  title: 开始节点 emitter
spec:
  allowedActions: []
  allowedEvents:
    - name: start
      title: 启动