@host=http://localhost:10001

### 新建emitter - 审批场景
POST {{host}}/emitters/
Content-Type: application/x-yaml

kind: workflow-transition-emitter
name: demo/approval
metadata:
  title: 审批场景 emitter
  forUserState: true
spec:
  actions:
    - action: ACCEPT
      title: 通过
      kind: decision
    - action: REFUSE
      title: 拒绝
      kind: decision
  allowedEvents:
    - name: passed
      title: 通过
      color: "#22c55e"
      icon: "check"
    - name: rejected
      title: 拒绝
      color: "#ef4444"
      icon: "x"

### 新建emitter - 开始节点
POST {{host}}/emitters/
Content-Type: application/x-yaml

kind: workflow-transition-emitter
name: system/start
metadata:
  title: 开始节点 emitter
  forUserState: false
spec:
  actions: []
  allowedEvents:
    - name: start
      title: 启动
      color: "#3b82f6"
      icon: "play"